### ISSUE TITLE
Custom click event for highlighted widget

### ISSUE THREAD

**Issue by dukaric1991** [simformsolutions/flutter_showcaseview#10]
Can i handle click event on highlighted widget? Now the flow is: you can only dismiss the showcase and then click on widget. 

I want to have, if user clicks on highlighted widget it goes to some screen, and only dissmis showcase if you click anywhere outside of highlighted widget.

Is that possible?

**Comment by simformsolutions** [comment]
@dukaric1991  please use newly added onTargetClick and disposeOnTap on showcase widget to make it work.
