### ISSUE TITLE
Multiline description

### ISSUE THREAD

**Issue by shangarivivek** [simformsolutions/flutter_showcaseview#12]
Hi,Thanks for this plugin, It will really helpful for me. can anyone help me to solve multiline description or how to set the height of showcase widget,I tried but its not working

**Comment by shangarivivek** [comment]
Customized a Contained width & description Text to multiline.Thanks again for this plugin.

**Comment by simformsolutions** [comment]
Hello @shangarivivek ,

Thank you for using our plugin.
Feel free to contect us if you face any issues in future.

Regards,
Simform Team.
