### ISSUE TITLE
Clicking on back button while using BottomSheet

### ISSUE THREAD

**Issue by marianoarga** [simformsolutions/flutter_showcaseview#16]
Clicking on back button does not dismiss the showCase, it remains as strange layout when using on a BottomSheet

**Comment by marianoarga** [comment]
Fixed awaiting for the bottomSheetController closed future:
```
await bottomSheetController.closed.then((_){
  ShowCaseWidget.dismiss(context);
});
```

**Comment by simformsolutions** [comment]
hi @marianoarga is it fixed or not ? btw thanks for using this.

**Comment by marianoarga** [comment]
@simformsolutions Yes, got fixed with the code I shared, you can close this issue now.
Thank *you* for coding it :)
