### ISSUE TITLE
ShowCaseView "finished" callback

### ISSUE THREAD

**Issue by marianoarga** [simformsolutions/flutter_showcaseview#17]
Is there any callback or method to know when showcase has been showed? in order to do something after all steps are finished.

**Comment by ziggycrane** [comment]
I second this. This seems like a must have.

**Comment by simformsolutions** [comment]
Good idea , We'll work on this btw you can send us PR if you get time. :)

**Comment by marcos930807** [comment]
I need This please.

**Comment by marianoarga** [comment]
For everyone commented on this issue, this is aplied in 0.1.3

```
ShowCaseWidget.setOnShowCaseFinish(() {
  _showSnakbar('ShowcaseView Finished');
});
```

Thanks to the developers

**Comment by marcos930807** [comment]
I am at 0.1.3 and I don't have that method

**Comment by marcos930807** [comment]
that method where removed!!!!!

**Comment by marianoarga** [comment]
@marcos930807 QA is still remaining
https://github.com/simformsolutions/flutter_showcaseview/commit/09e6d48cc9d1880e3f3ada49675c10bcfaca79b1#diff-0d9e9648c18bc243a7e72c5a1ee7509f

**Comment by SanketKachhela** [comment]
@marcos930807 This feature will be update tomorrow

**Comment by marcos930807** [comment]
I would appreciate it, for the moment I downloaded the lib and modified it by adding the commented lines, but it would be great to be able to use it directly from your package.
