### ISSUE TITLE
Disable animation on showcase widget

### ISSUE THREAD

**Issue by teenoh** [simformsolutions/flutter_showcaseview#22]
Thank you very much for this awesome package. Is there a way to disable the animation on the showcase widget? I have not been able to figure out how to do that.

**Comment by marcos930807** [comment]
Please I need this merge PR

**Comment by simformsolutions** [comment]
We have integrated new flag in `Showcase ` widget named `disableAnimation `,
Simply set this boolean to `true` to disable animation in any `Showcase`

**Comment by gxsham** [comment]
Hi everyone,

Would it be possible to disable the animations at the level of `ShowCaseWidget`? 
Seems a bit weird that if I want to disable all the animations I need to go through each 'Showcase'.
