### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by shaxxx** [simformsolutions/flutter_showcaseview#23]
First of all, thanks for great plugin.
But please update readme (and other docs if any) to reflect changes you've made in API.
Current code snippets don't work.

Also, I've lost half an hour fighting with MethodNotFound exception, even after reading docs and seeing issue https://github.com/simformsolutions/flutter_showcaseview/issues/9
My mistake yes, but I was really close to removing plugin and leaving everything behind.

Since I'm obviously not only one, README should be more explicit and clear about need of ShowCaseWidget. 

Once again, great plugin, thanks.

**Comment by simformsolutions** [comment]
Thank you for your review.
We will look for your recommendation, and update ReadMe file as soon as possible.
