### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by akshatjagga** [simformsolutions/flutter_showcaseview#26]
This library simply doesn't work and the documentation for it is so poor, making it unusable. Please fix the ReadMe. Getting - "Please provide ShowCaseView context" for no reason.

**Comment by DevarshRanpara** [comment]
Hi,
Can you share your code snippet and error log so that we can help you out to solve your problem.

And sure we will look after your recommendation to update whole documentation of package.

**Comment by rajeevjaiswal** [comment]
@DevarshRanpara Getting Please provide ShowCaseView context error

**Comment by simformsolutions** [comment]
@akshatjagga @rajeevjaiswal 
By mistake you are passing wrong `context` to `ShowCaseWidget.of(context).startShowCase([_one]) ` method.
You need to wrap your `Scaffold` with `ShowCaseWidget ` and pass `Builder` context of `ShowCaseWidget`.

Please refer [this](https://github.com/simformsolutions/flutter_showcaseview/blob/master/example/lib/detailscreen.dart) file for batter understanding.
