### ISSUE TITLE
Exception: Please provide ShowCaseView context

### ISSUE THREAD

**Issue by Gursewak-Uppal** [simformsolutions/flutter_showcaseview#28]
Code:

` @override
  void initState() {
    // TODO: implement initState
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback(
        (_) => ShowCaseWidget.of(context).startShowCase([profileKey]));
  }`

`   appBar: AppBar(
        title: Text('User Profile', style: TextStyle(color: Colors.white)),
        iconTheme: IconThemeData(
          color: Colors.white, //change your color here
        ),
        actions: <Widget>[
          ShowCaseWidget(
            builder: Builder(
                builder: (context) => Showcase(
                    key: profileKey,
                    child: InkWell(
                        onTap: () {
                          Navigator.of(context).push(MaterialPageRoute(
                              builder: (BuildContext context) =>
                                  EditProfile(widget.currentUser)));
                        },
                        child: Container(
                          height: 30,
                          width: 30,
                          child: SvgPicture.asset(UIData.editProfileIcon,
                              color: Colors.white, semanticsLabel: 'ranking'),
                        )),
                    description: 'Tap to edit profile')),
          ),
        ],
      )`

Logs:

Performing hot restart...
Syncing files to device iPhone 11 Pro...
Restarted application in 2,826ms.
	path: satisfied (Path is satisfied), interface: en0
flutter: en-US
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following _Exception was thrown during a scheduler callback:
flutter: Exception: Please provide ShowCaseView context
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ShowCaseWidget.of (package:showcaseview/showcase_widget.dart:21:7)
flutter: #1      _UserProfileState.initState.<anonymous closure> (package:full_gool/ui/pages/profile/UserProfile.dart:84:31)
flutter: #2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
flutter: #3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:983:9)
flutter: #4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
flutter: #8      _invoke (dart:ui/hooks.dart:249:10)
flutter: #9      _drawFrame (dart:ui/hooks.dart:207:3)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
	[C19.1 1E007A17-3E74-41EC-9097-B144DBB7C94B 192.168.1.7:55159<->172.217.166.206:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 62.345s, DNS @0.001s took 0.003s, TCP @0.004s took 0.014s, TLS took 0.106s
	bytes in/out: 11283/3709, packets in/out: 20/18, rtt: 0.014s, retransmitted packets: 1, out-of-order packets: 0

**Comment by rajeevjaiswal** [comment]
@Gursewak-Uppal  How did you solve this?

**Comment by sokheangkhun** [comment]
I got this error too.
