### ISSUE TITLE
Exception: Please provide ShowCaseView context

### ISSUE THREAD

**Issue by cgowthamanmca** [simformsolutions/flutter_showcaseview#29]
@override
  void initState() {
    bloc = BlocProvider.of<HomeUserConatinerBloc>(context);
    homeBloc = HomeFeedBloc(authenticationBloc: bloc.authenticationBloc);
    profileBloc = ProfileBloc();
    _controller = PageController(initialPage: 0, keepPage: true);
    trendBloc = TrendBloc();
    affiliatedProductMenuBloc = AffiliatedProductMenuBloc();
    super.initState();
    WidgetsBinding.instance
        .addPostFrameCallback((_) => ShowCaseWidget.of(context).startShowCase([
              _one,
            ]));
  }
@override
  Widget build(BuildContext context) {
    return ShowCaseWidget(
      builder: Builder(
        builder: (context) => Scaffold(
          backgroundColor: ColorResource.BLACKF9,
          bottomNavigationBar: FABBottomAppBar(
            color: ColorResource.BLACKB7,
            selectedColor: Colors.black,
            notchedShape: CircularNotchedRectangle(),
            onTabSelected: (page) {
              setState(() {
                selectedIndex = page;
              });
              if (page == 0) {
                if (!(homeBloc.state is HomeFeedDataLoadingState))
                  this.homeBloc.add(HomeFeedRefreshEvent());
              }
              bloc.add(HomeUserConatinerPageChangeEvent(page));
            },
            items: [
              FABBottomAppBarItem(
                  iconData: Icons.home,
                  text: '',
                  color: selectedIndex == 0
                      ? Colors.black
                      : ColorResource.BLACKB7),
              FABBottomAppBarItem(
                  iconData: Icons.trending_up,
                  text: '',
                  color: selectedIndex == 1
                      ? Colors.black
                      : ColorResource.BLACKB7),
              FABBottomAppBarItem(
                  iconData: Icons.shopping_basket,
                  text: '',
                  color: selectedIndex == 2
                      ? Colors.black
                      : ColorResource.BLACKB7),
              FABBottomAppBarItem(
                  iconData: Icons.more_horiz,
                  text: '',
                  color: selectedIndex == 3
                      ? Colors.black
                      : ColorResource.BLACKB7),
            ],
          ),
          floatingActionButtonLocation:
              FloatingActionButtonLocation.centerDocked,
          floatingActionButton: _buildFabImage(
              context), // This trailing comma makes auto-formatting nicer for build methods.
          appBar: AppBar(
            automaticallyImplyLeading: false,
            backgroundColor: Colors.white,
            elevation: 0.0,
            centerTitle: true,
            title: ToolbarTitle(
              StringResource.APP_NAME,
              font: Font.Yesteryear,
              fontSize: 29,
            ),
            actions: <Widget>[
              Image.asset(
                ImageConstant.NOTIFICATION,
                height: 18,
                width: 18,
              ),
              SizedBox(
                width: 16,
              ),
              InkWell(
                onTap: () {
                  Navigator.of(context).pushNamed(AppRoutes.viewed_product);
                },
                child: Image.asset(
                  ImageConstant.HISTORY,
                  height: 17,
                  width: 19,
                ),
              ),
              SizedBox(
                width: 16,
              )
            ],
          ),
          body: WillPopScope(
            onWillPop: onWillPop,
            child: BlocListener(
              bloc: bloc,
              listener: (BuildContext context, HomeUserConatinerState state) {
                if (state is HomeUserConatinerPageChangeState) {
                  _controller.animateToPage(bloc.page,
                      curve: Curves.linear,
                      duration: Duration(milliseconds: 250));
                }
              },
              child: _buidPage(),
            ),
          ),
        ),
      ),
    );

  Widget _buildFabImage(BuildContext context) {
    return Showcase(
        key: _one,
        description: 'Tap to check mail',
        child: FloatingActionButton(
          onPressed: () {
            Navigator.pushNamed(context, AppRoutes.createPost,
                arguments: homeBloc);
          },
          tooltip: 'Increment',
          child: Image.asset(ImageConstant.POST_BUTTON),
          elevation: 2.0,
        ));
  }

this error:
 ShowCaseWidget.of (package:showcaseview/showcase_widget.dart:21:7)
Syncing files to device vivo 1908...
I/flutter ( 6402): #1      _HomeUserContainerState.initState.<anonymous closure> (package:girlsourced/src/home/user/home_user_container/home_user_container.dart:68:53)
Syncing files to device vivo 1908...
I/flutter ( 6402): #2      SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1033:15)
Syncing files to device vivo 1908...
I/flutter ( 6402): #3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:983:9)
Syncing files to device vivo 1908...
I/flutter ( 6402): #4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
Syncing files to device vivo 1908...
I/flutter ( 6402): #5      _rootRun (dart:async/zone.dart:1124:13)
Syncing files to device vivo 1908...
I/flutter ( 6402): #6      _CustomZone.run (dart:async/zone.dart:1021:19)
Syncing files to device vivo 1908...
I/flutter ( 6402): #7      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
Syncing files to device vivo 1908...
I/flutter ( 6402): #8      _invoke (dart:ui/hooks.dart:249:10)
Syncing files to device vivo 1908...
I/flutter ( 6402): #9      _drawFrame (dart:ui/hooks.dart:207:3

**Comment by shubham-cueclad** [comment]
Write your code in side **WidgetsBinding.instance.addPostFrameCallback**

`WidgetsBinding.instance.addPostFrameCallback((_)async{
                               ShowCaseWidget.of(context).startShowCase([_one,_two,_three,_four,_five,_six,_seven,_eight,_nine]);
}); `

**Comment by cgowthamanmca** [comment]
Sorry my side issue please close the issue.Thanks

**Comment by simformsolutions** [comment]
@cgowthamanmca Closing issue as it was implementation mistake.

**Comment by bui3itf0ky00** [comment]
what was wrong with ur code? , because I have the same error !!

**Comment by phamvuong64** [comment]
> có gì sai với mã của bạn? , vì tôi cũng bị lỗi như vậy !!

me too

**Comment by bayuly94** [comment]
no solution ?

**Comment by DiegoVega19** [comment]
I'm getting the same error in widget testing, what is the solution?
