### ISSUE TITLE
Description overlap 

### ISSUE THREAD

**Issue by cgowthamanmca** [simformsolutions/flutter_showcaseview#31]
MyCode:

Showcase(
                          key: _two,
                          shapeBorder: CircleBorder(),
                          descTextStyle: TextStyle(
                              color: Colors.white,
                              fontSize: 16,
                              fontFamily: Font.RobotoRegular.value),
                          showcaseBackgroundColor: ColorResource.PINK,
                          description:
                              " Or choose outfits from retail  partners that suit your occasion.",
                          child: Image.asset(
                            ImageConstant.CART_ICON,
                            height: 59,
                            width: 59,
                          ),
                        ),
check this url 
https://ibb.co/1bJ8xMk

**Comment by simformsolutions** [comment]
i would say , use linebreak as of now , we'll check this.

**Comment by ElZombieIsra** [comment]
I have the same issue. The text overflows and extends the widget container over the screen size width.

I suggest that u add some form of "maxWidth" constrain to the container that holds the description so the text can overflow or wrap within the bounds of the screen

**Comment by APDos** [comment]
Is there any fix/update here? Currently running into this issue and adding '\n' to my String is making it look like this:

<img width="327" alt="Screen Shot 2020-10-06 at 9 26 55 PM" src="https://user-images.githubusercontent.com/11493442/95276995-ab3cea00-081a-11eb-8e6a-5367d60a81b8.png">
