### ISSUE TITLE
Multiple Widgets used the same Global Key

### ISSUE THREAD

**Issue by kamrancr7** [simformsolutions/flutter_showcaseview#35]
i got the following exception:

```
I/flutter (11385): Another exception was thrown: Multiple widgets used the same GlobalKey.
I/flutter (11385): Another exception was thrown: Duplicate GlobalKeys detected in widget tree.
```

**Comment by kamrancr7** [comment]
class _AcceptedOffersState extends State<AcceptedOffers> {

  GlobalKey _one = GlobalKey();
  GlobalKey _two = GlobalKey();
  BuildContext myContext;



init method:
WidgetsBinding.instance.addPostFrameCallback((_) => ShowCaseWidget.of(myContext).startShowCase([_one,_two]));


build method:
Widget build(BuildContext context) {
    return ShowCaseWidget(
        builder: Builder(
        builder: (context) {
      myContext = context;
      return Scaffold(
      body: _loading
          ? Center(
              child: CircularProgressIndicator(),
            )
          :
      SingleChildScrollView(
              child: Column(



ShowCase:
  Showcase(
                      key: _one,
                      description: 'Tap to see menu options',
                      child: Material(
                        color: Colors.greenAccent,
                        shape:  CircleBorder(),
                        child: IconButton(
                          onPressed: () {},
                          tooltip: "",

  Showcase(
                      key: _two,
                      description: 'Tap to see menu options',
                      child: Material(
                        color: Colors.blueAccent,
                        shape:  CircleBorder(),
                        child: IconButton(
                          onPressed: () {},
                          tooltip: "View location",

**Comment by 926** [comment]
> i got the following exception:
> 
> ```
> I/flutter (11385): Another exception was thrown: Multiple widgets used the same GlobalKey.
> I/flutter (11385): Another exception was thrown: Duplicate GlobalKeys detected in widget tree.
> ```

me too

**Comment by simformsolutions** [comment]
@926  & @kamrancr7  we're unable to re-produce this.  I assume it will not surely related to hot reload but please ensure and please go through these answer  https://stackoverflow.com/questions/49371221/duplicate-globalkey-detected-in-widget-tree

**Comment by GENL** [comment]
Hi, to solve this add 'new'.
Make
```
GlobalKey _one = new GlobalKey();
```
instead of: 
```
GlobalKey _one = new GlobalKey();
```
