### ISSUE TITLE
disableAnimation still not released despite being available in source code

### ISSUE THREAD

**Issue by shawnlah** [simformsolutions/flutter_showcaseview#36]
Hey, can I know when is disableAnimation going to be available? I noticed its already in the source code, thanks.

**Comment by BirjuVachhani** [comment]
@shawnlah Thanks for reporting this. We had planned to release this earlier but due to some reasons we were occupied with some other task. This will be published soon and we'll notify you when we do!

**Comment by DevarshRanpara** [comment]
Hi @shawnlah ,
Please update package with version `0.1.5`.
We have released `disableAnimation` in that version.
