### ISSUE TITLE
ShowCaseWidget.startShowCase is unknow.

### ISSUE THREAD

**Issue by Hakentha** [simformsolutions/flutter_showcaseview#43]
When i try to use ShowCaseWidget.startShowCase like documentation. It is unknow.

When i try to use like the example, trow me: Exception: Please provide ShowCaseView context.

**Comment by batoi-ivan** [comment]
Try this ShowCaseWidget.of(context).startShowCase([_one, _two, _three, _four, _five]));

**Comment by simformsolutions** [comment]
@Hakentha  let me know if you're still facing issue. 
btw thanks @batoi-ivan  for the help.

**Comment by CaptainDario** [comment]
I face the same problem @Hakentha encountered.
When I try this:
```
Try this ShowCaseWidget.of(context).startShowCase([_one, _two, _three, _four, _five]));
```
as @ivanmr97 suggests I get the error:
```
════════ Exception caught by scheduler library ═════════════════════════════════
The following _Exception was thrown during a scheduler callback:
Exception: Please provide ShowCaseView context

When the exception was thrown, this was the stack
#0      ShowCaseWidget.of (package:showcaseview/showcase_widget.dart:60:7)
#1      _DrawScreenState.build.<anonymous closure>
package:da_kanji_recognizer_mobile/DrawScreen.dart:26
```

any help would be greatly appreciated.

**Comment by Hakentha** [comment]
> Try this ShowCaseWidget.of(context).startShowCase([_one, _two, _three, _four, _five]));

Ty ivanmr97, unfortunately i dont read your response at time, sry. For the problem, i dont find a solution, i pass to bubble_showcase.
Thanks to all!

**Comment by CaptainDario** [comment]
The solution is to copy the showcase initialization from the example. Now it is working for me.
