### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by Solido** [simformsolutions/flutter_showcaseview#5]
Your lib is very pro and useful you're welcome to join 
https://github.com/Solido/awesome-flutter !
Thx

**Comment by simformsolutions** [comment]
Thanks @Solido for inviting us , should we create a new category named `Walkthrough` ? i think later someone can add other introduction plugin on the same.

**Comment by Solido** [comment]
No need for special for now because you're just the second implementation since the beginning of Flutter and yours is quite complete. Find a section that please you PR and later I can update. Thx !

**Comment by simformsolutions** [comment]
@Solido  Created a PR for the same , https://github.com/Solido/awesome-flutter/pull/518 
Please review. 

Thanks
