### ISSUE TITLE
Cannot add dependency to Java code

### ISSUE THREAD

**Issue by tvaknin** [simformsolutions/flutter_showcaseview#51]
There is no guide on how to add it to build.gradle

**Comment by AkramIzz** [comment]
This is a dart package. It doesn't include any platform-specific code, and hence you don't need to add anything to build.gradle for this package to work.

Just add it in your dependencies (the pubspec.yaml file) as described in the README of this repo.

**Comment by DevarshRanpara** [comment]
Hello @tvaknin ,
As @AkramIzz described, this is dart code and it does not need any platform specific code.
So you can use after just adding in your `pubspec.yaml` file as described in [README.md](https://github.com/simformsolutions/flutter_showcaseview/blob/master/README.md) file.
