### ISSUE TITLE
Getting NoSuchMethodError

### ISSUE THREAD

**Issue by mikeyyg96** [simformsolutions/flutter_showcaseview#9]
When I try to add a showcase widget in my app, I get the the NoSuchMethodError.
`GlobalKey _swipeKey = GlobalKey();`

`@override
void initState() {
super.initState();
WidgetsBinding.instance.addPostFrameCallback((_) =>ShowCaseWidget.startShowCase(context, [_swipeKey]));}`

`NoSuchMethodError: The getter 'activeWidgetIds' was called on null.`

**Comment by simformsolutions** [comment]
@mikeyyg96  are you passing `_swipeKey ` in `Showcase` widget's key parameter?

**Comment by ziggycrane** [comment]
Tried it out, I get the same message.

**Comment by ziggycrane** [comment]
This error is thrown if you haven't wrapped your widget with ShowCaseWidget. This is not the problem with the package itself.

**Comment by simformsolutions** [comment]
@ziggycrane 
Okay thank you for using our package,
Closing issue as it was implementation mistake.
